// Package trsparser provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package trsparser

// NonEmptyString defines model for NonEmptyString.
type NonEmptyString = string

// ParseError defines model for ParseError.
type ParseError struct {
	LlmMessage NonEmptyString `json:"llmMessage"`
	Summary    NonEmptyString `json:"summary"`
}

// Trs defines model for Trs.
type Trs struct {
	Interpretations []NonEmptyString `json:"interpretations"`
	Rules           []NonEmptyString `json:"rules"`
	Variables       []NonEmptyString `json:"variables"`
}
