repos:
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.2
    hooks:
      - id: go-fmt-import
  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.7
    hooks:
    - id: jupytext
      args: [--sync]
