version: '3'
services:
  llm:
    build:
      dockerfile: dockerfiles/llm.dockerfile
    container_name: llm
    # image: stewkk/tfl-lab1-llm:latest
  backend:
    build:
      dockerfile: ./dockerfiles/backend.dockerfile
    environment:
      TGTOKEN: "${TGTOKEN}"
    env_file: ".env"
    container_name: backend
    # image: stewkk/tfl-lab1-backend:latest
  interpret:
    build:
      dockerfile: ./dockerfiles/interpret.dockerfile
    container_name: interpret
    # image: stewkk/tfl-lab1-interpret:latest
