version: '3'
services:
  llm:
    build:
      dockerfile: dockerfiles/llm.dockerfile
    container_name: llm
    image: tlf-lab1-llm
  backend:
    build:
      dockerfile: ./dockerfiles/backend.dockerfile
    container_name: backend
    image: tlf-lab1-backend
  interpret:
    build:
      dockerfile: ./dockerfiles/interpret.dockerfile
    container_name: interpret
    image: tlf-lab1-interpret
