version: '3'
services:
  llm:
    build:
      dockerfile: dockerfiles/llm.dockerfile
    container_name: llm
    image: stewkk/tfl-lab1-llm:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 5s
      start_interval: 5s
  backend:
    build:
      dockerfile: ./dockerfiles/backend.dockerfile
    environment:
      TGTOKEN: "${TGTOKEN}"
    env_file: ".env"
    container_name: backend
    image: stewkk/tfl-lab1-backend:latest
    depends_on:
      llm:
        condition: service_healthy
      interpret:
        condition: service_healthy
  interpret:
    build:
      dockerfile: ./dockerfiles/interpret.dockerfile
    container_name: interpret
    image: stewkk/tfl-lab1-interpret:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 5s
      start_interval: 5s
