apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: llm-service
spec:
  selector:
    app: llm
  ports:
    - port: 8100
      targetPort: 8100
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: formalize-service
spec:
  selector:
    app: formalize
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: interpret-service
spec:
  selector:
    app: interpret
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
