apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8443
      targetPort: 8443
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: llm
spec:
  selector:
    app: llm
  ports:
    - port: 8100
      targetPort: 8100
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: formalize
spec:
  selector:
    app: formalize
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: interpret
spec:
  selector:
    app: interpret
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: llm-balancer
spec:
  selector:
    app: llm-balancer
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
