package: interpretclient
output: client.gen.go
generate:
  models: true
  client: true
output-options:
  skip-prune: false
import-mapping:
  trs-parser-api.yaml: github.com/BaldiSlayer/rofl-lab1/pkg/trsparser
