apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'tfl-lab1'
spec:
  destination:
    name: 'in-cluster'
    namespace: 'prod'
  source:
    path: 'chart'
    repoURL: 'https://github.com/BaldiSlayer/rofl-lab1'
    targetRevision: new-deploy
    helm:
      valueFiles:
        - values.yaml
  project: 'default'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true