from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ConstantMonomial(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, constant=None):  # noqa: E501
        """ConstantMonomial - a model defined in OpenAPI

        :param constant: The constant of this ConstantMonomial.  # noqa: E501
        :type constant: int
        """
        self.openapi_types = {
            'constant': int
        }

        self.attribute_map = {
            'constant': 'constant'
        }

        self._constant = constant

    @classmethod
    def from_dict(cls, dikt) -> 'ConstantMonomial':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConstantMonomial of this ConstantMonomial.  # noqa: E501
        :rtype: ConstantMonomial
        """
        return util.deserialize_model(dikt, cls)

    @property
    def constant(self) -> int:
        """Gets the constant of this ConstantMonomial.


        :return: The constant of this ConstantMonomial.
        :rtype: int
        """
        return self._constant

    @constant.setter
    def constant(self, constant: int):
        """Sets the constant of this ConstantMonomial.


        :param constant: The constant of this ConstantMonomial.
        :type constant: int
        """
        if constant is None:
            raise ValueError("Invalid value for `constant`, must not be `None`")  # noqa: E501
        if constant is not None and constant < 1:  # noqa: E501
            raise ValueError("Invalid value for `constant`, must be a value greater than or equal to `1`")  # noqa: E501

        self._constant = constant
