from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.factor import Factor
from openapi_server import util

from openapi_server.models.factor import Factor  # noqa: E501


class ProductMonomial(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, factors=None):  # noqa: E501
        """ProductMonomial - a model defined in OpenAPI

        :param factors: The factors of this ProductMonomial.  # noqa: E501
        :type factors: List[Factor]
        """
        self.openapi_types = {
            'factors': List[Factor]
        }

        self.attribute_map = {
            'factors': 'factors'
        }

        self._factors = factors

    @classmethod
    def from_dict(cls, dikt) -> 'ProductMonomial':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductMonomial of this ProductMonomial.  # noqa: E501
        :rtype: ProductMonomial
        """
        return util.deserialize_model(dikt, cls)

    @property
    def factors(self) -> List[Factor]:
        """Gets the factors of this ProductMonomial.


        :return: The factors of this ProductMonomial.
        :rtype: List[Factor]
        """
        return self._factors

    @factors.setter
    def factors(self, factors: List[Factor]):
        """Sets the factors of this ProductMonomial.


        :param factors: The factors of this ProductMonomial.
        :type factors: List[Factor]
        """
        if factors is None:
            raise ValueError("Invalid value for `factors`, must not be `None`")  # noqa: E501
        if factors is not None and len(factors) < 1:
            raise ValueError("Invalid value for `factors`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._factors = factors
