openapi: 3.0.0
info:
  title: Interpret part API
  version: 0.1.0
servers:
- description: Local server
  url: http://localhost:8080/
paths:
  /ping:
    get:
      operationId: healthcheck
      responses:
        "200":
          description: OK
      summary: Healthcheck
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /trs/interpret:
    post:
      operationId: trs_interpret
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trs'
        description: Trs
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterpretResult'
          description: OK
      summary: Check decidability of trs
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    InterpretResult:
      example:
        answer: answer
      properties:
        answer:
          title: answer
          type: string
      required:
      - answer
      title: InterpretResult
      type: object
    Trs:
      example:
        variables:
        - null
        - null
        rules:
        - null
        - null
        interpretations:
        - null
        - null
      properties:
        variables:
          items:
            $ref: '#/components/schemas/NonEmptyString'
          minItems: 1
          title: variables
          type: array
        rules:
          items:
            $ref: '#/components/schemas/NonEmptyString'
          minItems: 1
          title: rules
          type: array
        interpretations:
          items:
            $ref: '#/components/schemas/NonEmptyString'
          minItems: 1
          title: interpretations
          type: array
      required:
      - interpretations
      - rules
      - variables
      title: Trs
      type: object
    NonEmptyString:
      minLength: 1
      title: NonEmptyString
      type: string
