openapi: 3.0.0
info:
  title: Formalize part API
  version: 0.1.0
servers:
- description: Local server
  url: http://localhost:8080/
paths:
  /ping:
    get:
      operationId: healthcheck
      responses:
        "200":
          description: OK
      summary: Healthcheck
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /trs/fix:
    post:
      operationId: trs_fix
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FixRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FixResponse'
          description: OK
      summary: Fix extracted formal definition of trs
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /trs/formalize:
    post:
      operationId: trs_formalize
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormalizeRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormalizeResult'
          description: OK
      summary: Extract formal definition of trs
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    FormalizeRequest:
      example:
        trs: trs
      properties:
        trs:
          title: trs
          type: string
      required:
      - trs
      title: FormalizeRequest
      type: object
    FormalizeResult:
      example:
        formalTrs: formalTrs
        error: error
      properties:
        formalTrs:
          title: formalTrs
          type: string
        error:
          title: error
          type: string
      required:
      - formalTrs
      title: FormalizeResult
      type: object
    FixRequest:
      example:
        formalTrs: formalTrs
        trs: trs
        error: error
      properties:
        trs:
          title: trs
          type: string
        formalTrs:
          title: formalTrs
          type: string
        error:
          title: error
          type: string
      required:
      - error
      - formalTrs
      - trs
      title: FixRequest
      type: object
    FixResponse:
      example:
        formalTrs: formalTrs
        error: error
      properties:
        formalTrs:
          title: formalTrs
          type: string
        error:
          title: error
          type: string
      required:
      - formalTrs
      title: FixResponse
      type: object
