# coding: utf-8

"""
    TFL

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.question_answer import QuestionAnswer
from typing import Optional, Set
from typing_extensions import Self


class ProcessQuestionsRequest(BaseModel):
    """
    ProcessQuestionsRequest
    """  # noqa: E501
    questions_list: List[QuestionAnswer]
    use_saved: Optional[StrictBool] = False
    filename: Optional[StrictStr] = 'vectorized_data'
    __properties: ClassVar[List[str]] = [
        "questions_list", "use_saved", "filename"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProcessQuestionsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in questions_list (list)
        _items = []
        if self.questions_list:
            for _item in self.questions_list:
                if _item:
                    _items.append(_item.to_dict())
            _dict['questions_list'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProcessQuestionsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "questions_list": [QuestionAnswer.from_dict(_item) for _item in obj["questions_list"]] if obj.get("questions_list") is not None else None,
            "use_saved": obj.get("use_saved") if obj.get("use_saved") is not None else False,
            "filename": obj.get("filename") if obj.get("filename") is not None else 'vectorized_data'
        })
        return _obj
