openapi: 3.0.0
info:
  title: Interpret part API
  version: 0.1.0
servers:
  - url: http://localhost:8080/
    description: Local server

paths:
  /trs/interpret:
    post:
      summary: Check decidability of trs
      operationId: trsInterpret
      requestBody:
        description: Trs
        required: true
        content:
          application/json:
            schema:
              $ref: 'trs-parser-api.yaml#/components/schemas/Trs'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterpretResult'

components:
  schemas:
    InterpretResult:
      type: object
      required:
        - answer
      properties:
        answer:
          type: string
