openapi: 3.0.0
info:
  title: TFL
  version: 0.0.1
paths:
  /search_similar:
    post:
      tags:
        - Questions
      summary: Api Process Questions
      operationId: api_process_questions_process_questions_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchSimilarRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchSimilarResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /get_chat_response:
    post:
      tags:
        - Questions
      summary: Api Get Chat Response
      operationId: api_get_chat_response_get_chat_response_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetChatResponseRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetChatResponseResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    GetChatResponseRequest:
      properties:
        prompt:
          type: string
          title: Prompt
        context:
          type: string
          title: Context
        model:
          type: string
          title: Model
          default: mistral-large-2411
      type: object
      required:
        - prompt
      title: GetChatResponseRequest
    GetChatResponseResponse:
      properties:
        response:
          type: string
      type: object
      required:
        - response
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    SearchSimilarRequest:
      properties:
        question:
          type: string
          title: question
      type: object
      required:
        - question
      title: ProcessQuestionsRequest
    SearchSimilarResponse:
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/QuestionAnswer'
          title: result
      type: object
      required:
        - result
    QuestionAnswer:
      properties:
        question:
          type: string
          title: Question
        answer:
          type: string
          title: Answer
      type: object
      required:
        - question
        - answer
      title: QuestionAnswer
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
