openapi: 3.0.0
info:
  title: TRS parser
  description: |
    Term Rewrite System formal parser
  version: 0.1.0

paths: {}

components:
  schemas:
    Trs:
      type: object
      required:
        - variables
        - rules
        - interpretations
      properties:
        variables:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/NonEmptyString'
        rules:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/NonEmptyString'
        interpretations:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/NonEmptyString'
    ParseError:
      type: object
      required:
        - llmMessage
        - summary
      properties:
        llmMessage:
          $ref: '#/components/schemas/NonEmptyString'
        summary:
          $ref: '#/components/schemas/NonEmptyString'
    NonEmptyString:
      type: string
      minLength: 1
