openapi: 3.0.0
info:
  title: TRS parser
  description: |
    Term Rewrite System formal parser
  version: 0.1.0

paths: {}

components:
  schemas:
    Trs:
      type: object
      required:
        - variables
        - rules
        - interpretations
      properties:
        variables:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/NonEmptyString'
        rules:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Rule'
        interpretations:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Interpretation'
    ParseError:
      type: object
      required:
        - llmMessage
        - summary
      properties:
        llmMessage:
          $ref: '#/components/schemas/NonEmptyString'
        summary:
          $ref: '#/components/schemas/NonEmptyString'
    Rule:
      type: object
      required:
        - lhs
        - rhs
      properties:
        lhs:
          $ref: '#/components/schemas/Subexpression'
        rhs:
          $ref: '#/components/schemas/Subexpression'
    Subexpression:
      type: object
      required:
        - letter
      properties:
        letter:
          $ref: '#/components/schemas/Letter'
        args:
          type: array
          items:
            schema:
              type: object
              description: Subexpression object
              additionalProperties: true

    Letter:
      type: object
      description: represents variable or constructor
      required:
        - name
        - isVariable
      properties:
        name:
          $ref: '#/components/schemas/NonEmptyString'
        isVariable:
          type: boolean
    Interpretation:
      type: object
      required:
        - name
        - args
        - monomials
      properties:
        name:
          $ref: '#/components/schemas/NonEmptyString'
        args:
          type: array
          items:
            $ref: '#/components/schemas/NonEmptyString'
        monomials:
          type: array
          items:
            $ref: '#/components/schemas/Monomial'
    Monomial:
      type: object
      oneOf:
        - $ref: '#/components/schemas/ProductMonomial'
        - $ref: '#/components/schemas/ConstantMonomial'
    ConstantMonomial:
      type: object
      required:
        - constant
      properties:
        constant:
          type: integer
          minimum: 1
    ProductMonomial:
      type: object
      required:
        - factors
      properties:
        factors:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Factor'
    Factor:
      type: object
      required:
        - variable
      properties:
        variable:
          $ref: '#/components/schemas/NonEmptyString'
        coefficient:
          type: integer
          minimum: 1
        power:
          type: integer
          minimum: 1
    NonEmptyString:
      type: string
      minLength: 1
