openapi: 3.0.0
info:
  title: TRS parser
  description: |
    Term Rewrite System formal parser
  version: 0.1.0
servers:
  - url: http://localhost:8080/
    description: Local

paths:
  /ping:
    get:
      summary: Healthcheck
      operationId: ping
      responses:
        '200':
          description: OK
  /trs/parse:
    post:
      summary: Parse TRS
      operationId: parseTrs
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - trs
              properties:
                trs:
                  $ref: '#/components/schemas/NonEmptyString'
      responses:
        '200':
          description: |
            OK. Returns parse error description or parsed trs
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/ParseError'
                  - $ref: '#/components/schemas/Trs'
        default:
          $ref: '#/components/responses/ErrorResponse'
components:
  responses:
    ErrorResponse:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/NonEmptyString'
      required:
        - message
    Trs:
      type: object
      required:
        - variables
        - rules
        - interpretations
      properties:
        variables:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/NonEmptyString'
        rules:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Rule'
        interpretations:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Interpretation'

    ParseError:
      type: object
      required:
        - line
        - range
        - summary
      properties:
        summary:
          $ref: '#/components/schemas/NonEmptyString'
        message:
          $ref: '#/components/schemas/NonEmptyString'
        line:
          type: integer
        range:
          type: object
          required:
            - from
            - to
          properties:
            from:
              type: integer
            to:
              type: integer
    Rule:
      type: object
      required:
        - lhs
        - rhs
      properties:
        lhs:
          $ref: '#/components/schemas/Subexpression'
        rhs:
          $ref: '#/components/schemas/Subexpression'
    Subexpression:
      type: object
      required:
        - letter
      properties:
        letter:
          $ref: '#/components/schemas/Letter'
        args:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Subexpression'
    Letter:
      type: object
      description: Variable or constructor
      required:
        - name
        - isVariable
      properties:
        name:
          $ref: '#/components/schemas/NonEmptyString'
        isVariable:
          type: boolean
    Interpretation:
      type: object
      oneOf:
        - $ref: '#/components/schemas/ConstInterpretation'
        - $ref: '#/components/schemas/ConstructorInterpretation'
    ConstInterpretation:
      type: object
      required:
        - name
        - value
      properties:
        name:
          $ref: '#/components/schemas/NonEmptyString'
        value:
          $ref: '#/components/schemas/NonEmptyString'
    ConstructorInterpretation:
      type: object
      required:
        - name
        - args
        - value
      properties:
        name:
          $ref: '#/components/schemas/NonEmptyString'
        args:
          type: array
          items:
            $ref: '#/components/schemas/NonEmptyString'
        value:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/Monomial'
              - $ref: '#/components/schemas/Constant'
    Monomial:
      type: object
      required:
        - variable
      properties:
        variable:
          $ref: '#/components/schemas/NonEmptyString'
        coefficient:
          type: integer
          minimum: 1
        power:
          type: integer
          minimum: 1
    Constant:
      type: integer
    NonEmptyString:
      type: string
      minLength: 1
