name: Jsonlint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Jsonlint
      uses: ixxeL-actions/jsonlint@main
      with:
        extensions: '"json,JSON"'
        fix: 'true'
