name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
        continue-on-error: true
        id: pre-commit
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.pre-commit.status == failure()
        with:
          commit_message: Apply pre-commit changes
