name: Yamllint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Yamllint
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_config_filepath: .yamllint-config.yaml
